### ISSUE TITLE
IAM Capability Required

### ISSUE THREAD

**Issue by nvisium-john-poulin** [awslabs/aws-cognito-apigw-angular-auth#13]
The `aws cloudformation deploy` command does not indicate that it needs `--capabilities CAPABILITY_IAM` and as such, errors with the following message during execution:

```
An error occurred (InsufficientCapabilitiesException) when calling the ExecuteChangeSet operation: Requires capabilities : [CAPABILITY_IAM]
```

I understand that it may not be ideal to include this option by default, so that users are aware of the security repercussions, but I think it should be covered in the documentation, at minimum.

Overall, thanks for this example. It is exactly what I was looking for!

**Comment by KoldBrewEd** [comment]
You're welcome! This is already in the README instructions:

"aws cloudformation deploy --template-file /Users/<username>/GitHub/aws-cognito-apigw-angular-auth/sam/sam-output.yaml --stack-name CognitoAPIGWDemo --capabilities CAPABILITY_IAM"

**Comment by nvisium-john-poulin** [comment]
Thanks for mentioning that is is in the README. I would recommend calling it out more, because by default the `aws cloudformation package` command does not return that flag, as you seen in my below screenshot. 

![screen shot 2018-03-08 at 11 31 10 am](https://user-images.githubusercontent.com/26073088/37162827-3f56bf98-22c4-11e8-873c-64698deb2ff2.png)

Since the README's sample command requires scrolling, it's very easy to miss, as you can see below:

<img width="949" alt="screen shot 2018-03-08 at 11 32 41 am" src="https://user-images.githubusercontent.com/26073088/37162947-93d52168-22c4-11e8-9623-7879df2f098e.png">
