### ISSUE TITLE
Security Issue on Posting user attributes

### ISSUE THREAD

**Issue by farminf** [awslabs/aws-cognito-apigw-angular-auth#16]
Hi,

IMHO, sending email,name,surname and ... in the body of the POST is not the best approach.
How can I get these attributes in my lmbda function only by having "cognitoIdentityId"?

I imagine that if I call some service I can get these attributes, because I don't trust the client to send these informations...

Thanks,

**Comment by KoldBrewEd** [comment]
This is not a security issue, just an implementation option to showcase an approach sending data over POST. You can use a JWT token from user pools that contains specific claims from the user with that info instead.
