### ISSUE TITLE
How to deploy aws-cognito-apigw-angular project to a server

### ISSUE THREAD

**Issue by gmarchand** [awslabs/aws-cognito-apigw-angular-auth#18]
How to deploy Angular project in production mode to an EC2 Instance, perhaps with PM2, Nginx ?

**Comment by gmarchand** [comment]
`ng build --prod` doesn't not work 
```
ERROR in ng:///Users/XXX/Documents/aws-cognito-apigw-angular/src/app/app.component.html (36,45): Supplied parameters do not match any signature of call target.
ng:///Users/XXX/Documents/aws-cognito-apigw-angular/src/app/app.component.html (37,65): Supplied parameters do not match any signature of call target.
ng:///Users/XXX/Documents/aws-cognito-apigw-angular/src/app/app.component.html (38,65): Supplied parameters do not match any signature of call target.
ng:///Users/XXX/Documents/aws-cognito-apigw-angular/src/app/app.component.html (43,55): Supplied parameters do not match any signature of call target.
```
1. Use `ng build --prod --aot=false` to solve this issue
2. Create a Static Website on Amazon S3 https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
3. copy `apiGateway-js-dsk`directory into the new `dist` directory
3. copy the new `dist`directory to the S3 bucket

**Comment by KoldBrewEd** [comment]
This is not an issue with this particular repo or code. It's related to deploying Angular builds to a web server. Suggest to take a look at https://angular.io/guide/deployment
