### ISSUE TITLE
CUPGroupRole not well named

### ISSUE THREAD

**Issue by gmarchand** [awslabs/aws-cognito-apigw-angular-auth#19]
https://github.com/aws-samples/aws-cognito-apigw-angular-auth/blob/master/sam/sam.yaml#L516

The role `CUPGroupRole`, used in `CognitoCIPGroup` includes a policy name `CognitoAPIGWAngularCIP`, allowing `"*/GET/cip"]`

```
 CUPGroupRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
```
Shouldn't this role named `CIPGroupRole` instead of `CUPGroupRole` ?

**Comment by KoldBrewEd** [comment]
Thankyou for the suggestion. Please create a pull request and I'll merge the changes.
