### ISSUE TITLE
React + Graphql example?

### ISSUE THREAD

**Issue by dalerka** [awslabs/aws-cognito-apigw-angular-auth#2]
Hi, thanks for sharing this. 
Is there such example using React and Graphql-server and demonstrating some best practices (up to the moment) for separate roles and permissions (regular users can modify own content, admins can modify all)?

**Comment by KoldBrewEd** [comment]
Thank you for the feedback. Unfortunately we don't have an example using another framework yet, however I'll discuss your suggestion with our internal teams and maybe in the future we can work on something related. Keep an eye on our AWS Blogs and other repos from awslabs, we are always releasing new sample code for different services and use cases.
