### ISSUE TITLE
Updating Readme Step2

### ISSUE THREAD

**Issue by alfrepo** [awslabs/aws-cognito-apigw-angular-auth#21]
Step 2 
MIssing parameters for the deploy command:

`aws cloudformation deploy --templ ate-file /mnt/c/1REPOS/aws-cognito-apigw-angular-auth/sam/sam-output.yaml --stack-name "awscognitoapigwangularauth" --capabilities CAPABILITY_IAM`

**Comment by KoldBrewEd** [comment]
README already has the parameters
