### ISSUE TITLE
Updating Readme step 2 (need aws configure)

### ISSUE THREAD

**Issue by sgrillon14** [awslabs/aws-cognito-apigw-angular-auth#23]
I execute `aws cloudformation package ....`  OK

I execute `aws cloudformation deploy ....`  KO with this message: "You must specify a region. You can also configure your region by running "aws configure".

Can you add "how to find `AWS Access Key ID`,  `AWS Secret Access Key`, ... ?" and "how to create a good IAM account?"

**Comment by sgrillon14** [comment]
for the moment I created a user with rights: AdministratorAccess

**Comment by KoldBrewEd** [comment]
You can find this information here: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
