### ISSUE TITLE
sam.yaml cannot be deployed: nodejs version too old

### ISSUE THREAD

**Issue by dirkgomez** [awslabs/aws-cognito-apigw-angular-auth#24]
sam.yaml cannot be deployed anymore, the referenced nodejs version is too old,Lambda suggests  nodejs8.10 instead of nodejs4.3

`The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions.`

**Comment by KoldBrewEd** [comment]
PR Merged, runtime now updated to 8.10
