### ISSUE TITLE
Instructions not clear

### ISSUE THREAD

**Issue by meije702** [awslabs/aws-cognito-apigw-angular-auth#3]
First thanks for making this, it is impossible to get anything working on AWS without an example the documentation is horrendous...

So I tried following your steps in the readme but gut stuck on step 11.
In the last part of step 10 you say unzip the downloaded apigwsdk.zip
Now I have done this but there is no /src folder or package.json file in there for me to copy.

I tried downloading this repo and installing it but that didn't work
I also tried to copy the /src and package.json from this repo to the CLI generated directory but that didn't work either.

So what do you actually mean by step 11, where are these items coming from?

**Comment by odinseyeanalytics** [comment]
I also ran into this issue.  Here is how I think it should be clarified:

Step 0) Clone the repo and make any edits to files in further steps (i.e. 1,2 and 4) in there (i.e. edit sam.yaml and aws.service.ts).

When you get to step 10, you now have two repos that are very similar, but obviously not identical.  

Copy the /src directory and package.json that you edited from the git repo clone (Step 0) into the directory created in step 10, overwriting the newly created files.

Then run the npm install and npm start and it should run.



Note to the owner of the README - please update the documentation to clarify where the /src and package.json should come from.  

Something like:
11. Copy the folder "/src" and the file "package.json" _**from steps 1-4**_ to the newly created folder "aws-cognito-apigw-angular" from the last step, overwriting the existing files.

Also, add a step directing users to clone the repo and make edits there (seems obvious, but not always for those of us trying to explore something new and unfamiliar).

**Comment by KoldBrewEd** [comment]
Thank you for the suggestions to improve the instructions, it will indeed make more clear. 

You need to clone this repository, made some changes to specific files, then create a new blank Angular CLI project, copy the modified files to it then run npm install/start.

I added the suggestions to the README.MD file.
