### ISSUE TITLE
Authenticated Role Selection

### ISSUE THREAD

**Issue by snowake4me** [awslabs/aws-cognito-apigw-angular-auth#7]
I'm guessing the Cognito UI has been updated (likely multiple times?) since this project was published - and mostly, I'm able to keep up with the transition / translation.  For example, in step 6 of the README there is (not currently) a section called AUTHENTICATION PROVIDERS - but Identity Providers is certainly close enough, and indeed, I found the referenced objects in that section.

But in Step 7 - try as I might - I can **not** find a "Cognito Tab" - nor, poring over every panel/tab/pane of the UI within the Identity Pool, can I find any reference to "AUTHENTICATED ROLE SELECTION" or the option to "CHOOSE ROLE FROM TOKEN".

I so desperately want this to work, as it alleges to demonstrate exactly what I've been struggling with for days now, and have failed with every previous AWS-documented, AWSlabs git repo that has anything to do with integrating Google (now G Suite) authentication with Cognito.

In the meantime, I'm back to plain ol' OAuth and OpenID Connect, in a 'roll-your-own' fashion - but I know that Cognito has value for our effort, and will save us much heavy lifting.

Any advice on what I'm doing wrong - or where this configuration may have migrated in the UI?  I'd gladly do it via the CLI / API if I had any confident in what I was supposed to be setting, etc.

Thanks in advance,

**Comment by KoldBrewEd** [comment]
It seems you are looking in the Cognito User Pools console. The configuration options on steps 6 and 7 are actually at the Cognito Federated Identities console when you edit your Identity Pool. Give it a try.

We released a new feature at Cognito User Pools called Federation Integration and that was indeed available after this code was published. You can take a look at a sample with the new features on https://github.com/aws/amazon-cognito-auth-js. Basically now you can federate without identity pools.

**Comment by KoldBrewEd** [comment]
Added FEDERATED IDENTITIES mention on step 6 to clarify the console location. Closing.
